CREATE TABLE IF NOT EXISTS stomatognathic_test  (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  lastissimus_dors_1r integer, 
  lastissimus_dors_1l integer, 
  lastissimus_dors_2r integer, 
  lastissimus_dors_2l integer, 
  lastissimus_dors_3r integer,   
  lastissimus_dors_3l integer, 
  lastissimus_dors_4r integer, 
  lastissimus_dors_4l integer, 
  lastissimus_dors_5r integer, 
  lastissimus_dors_5l integer, 
  neck_flex_r integer, 
  neck_flex_l integer, 
  neck_extflex_r integer, 
  neck_extflex_l integer, 
  sterncleid_r integer, 
  sterncleid_l integer, 
  rectfem_r integer, 
  rectfem_l integer, 
  pirif_r integer, 
  pirif_l integer, 
  iliopsoas_r integer, 
  iliopsoas_l integer, 

  cat1_err boolean,
  cat1_err_pos varchar(64), 
  cat2_err_r integer,
  cat2_err_l integer,
  
  inicator varchar(64), 
    
  tl_okziput integer,
  double_tl_cat integer,
  double_tl_okz integer,
  
  ruheschwebe_r varchar(64), 
  ruheschwebe_l varchar(64), 
  fester_r varchar(64), 
  fester_l varchar(64), 
  weite_off_r varchar(64), 
  weite_off_l varchar(64),  
  
  priener_abduck_ein boolean,
  priener_abduck_ander boolean,
  torax_rotat boolean,
  meersemann boolean,
  
  m_klefergelenk_lat_r integer,
  m_klefergelenk_lat_l integer,
  m_klefergelenk_dor_r integer,
  m_klefergelenk_dor_l integer,
  m_klefergelenk_kompr_r integer,
  m_klefergelenk_kompr_l integer,
  m_masseter_prof_r integer,
  m_masseter_prof_l integer,
  m_masseter_sup_r integer,
  m_masseter_sup_l integer,
  m_temporalis_ant_r integer,
  m_temporalis_ant_l integer,
  m_temporalis_post_r integer,
  m_temporalis_post_l integer,
  m_suboccip_r integer,
  m_suboccip_l integer,
  m_trapezius_r integer,
  m_trapezius_l integer,
  m_sterncleid_r integer, 
  m_sterncleid_l integer, 
  m_digastr_r integer, 
  m_digastr_l integer, 
  m_temporaliss_r integer, 
  m_temporaliss_l integer, 
  m_pterygoid_lat_r integer, 
  m_pterygoid_lat_l integer, 
  m_pterygoid_med_r integer, 
  m_pterygoid_med_l integer, 
  m_scaleni_r integer, 
  m_scaleni_l integer, 
  
  c0_r integer, 
  c0_l integer, 
  c0_d integer, 
  c1_r integer, 
  c1_l integer, 
  c1_d integer,
  c2_r integer, 
  c2_l integer, 
  c2_d integer,
  c3_r integer, 
  c3_l integer, 
  c3_d integer, 
  c4_r integer, 
  c4_l integer, 
  c4_d integer, 
  c5_r integer, 
  c5_l integer, 
  c5_d integer, 
  g_r integer, 
  g_l integer, 
  g_d integer, 
  t1_r integer, 
  t1_l integer, 
  t1_d integer,
  t2_r integer, 
  t2_l integer, 
  t2_d integer,

  customer_id uuid not null REFERENCES customers(id)
);