CREATE TABLE IF NOT EXISTS recent_anamnesys (
  id serial NOT NULL, 
  main_disease_1 varchar(256),  
  main_disease_2 varchar(256),  
  main_disease_3 varchar(256),  
  main_disease_4 varchar(256),  
  main_disease_5 varchar(256), 
  global_health varchar(256), 
  other_diseases varchar(256), 
  disease_in_life integer, 
  disease_in_family integer, 
  disease_in_work integer, 
  disease_in_social integer, 
  posture varchar(256), 
  medicine varchar(256), 
  pre_treatment varchar(256), 
  main_disease_intensity integer,
  main_disease_description varchar(256),  
  main_disease_date date,  
  main_disease_modality varchar(256),  
  main_disease_course varchar(256),  
  main_disease_factor_plus varchar(256),  
  main_disease_factor_minor varchar(256),  
  main_disease_nervous_system varchar(256),
  main_disease_symptoms_24 varchar(256),  
  images_diagnostics varchar(256),  
  customer_id INTEGER not null REFERENCES customers(id),
  PRIMARY KEY (id)  
);

CREATE TABLE IF NOT EXISTS remote_anamnesys (
  id serial NOT NULL, 
  phisical_disease varchar(256),  
  psychic_disease varchar(256),  
  surgery varchar(256),  
  anesthesias varchar(256),  
  pregnancy varchar(256),  
  traumas varchar(256), 
  recent_episodes varchar(256), 
  recent_treatments varchar(256), 
  medicines varchar(256), 
  other varchar(256), 
  customer_id INTEGER not null REFERENCES customers(id),
  PRIMARY KEY (id)  
);